### ISSUE TITLE
关于 ghidra使用 jni_helper

### ISSUE THREAD

**Issue by Jokky6** [evilpan/jni_helper#4]
缺少 app-debug.json 导致 helper无法运行，可以提供一些 jni_helper.json 示例么？

**Comment by evilpan** [comment]
需要使用 [JadxFindJNI.jar](https://github.com/evilpan/jni_helper/tree/master/JadxFindJNI) 来生成对应 APK 的 signature.json:

```bash
$ java -jar JadxFindJNI.jar
Usage: JadxFindJNI.jar <file.apk> <output.json>
```

**Comment by evilpan** [comment]
Update:
新版 jni_helper 可直接使用 [extract_jni.py](https://github.com/evilpan/jni_helper#extract_jnipy) 来从 APK 中提取 signature.json，即 JNI 函数签名信息。
