### ISSUE TITLE
JNI Helper for IDA can't use in IDA PRO 7.6 SP1

### ISSUE THREAD

**Issue by xmhwws** [evilpan/jni_helper#5]
IDA PRO 7.6 SP1、python3.9.1，一运行IDA就是如下提示：

```
D:\IDA7.6\plugins\jni_helper3.py: invalid syntax (D:/IDA7.6/plugins/jni_helper3.py, line 7)
Traceback (most recent call last):
  File "D:\IDA7.6\python\3\ida_idaapi.py", line 615, in IDAPython_ExecScript
    code = compile(raw.decode(encoding), path, 'exec')
  File "D:/IDA7.6/plugins/jni_helper3.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
```

**Comment by evilpan** [comment]
> IDA PRO 7.6 SP1、python3.9.1，一运行IDA就是如下提示：
> 
> ```
> D:\IDA7.6\plugins\jni_helper3.py: invalid syntax (D:/IDA7.6/plugins/jni_helper3.py, line 7)
> Traceback (most recent call last):
>   File "D:\IDA7.6\python\3\ida_idaapi.py", line 615, in IDAPython_ExecScript
>     code = compile(raw.decode(encoding), path, 'exec')
>   File "D:/IDA7.6/plugins/jni_helper3.py", line 7
>     <!DOCTYPE html>
>     ^
> SyntaxError: invalid syntax
> ```

检查一下 `D:/IDA7.6/plugins/jni_helper3.py` 文件的内容，看起来你这是个 HTML 文件

**Comment by xmhwws** [comment]
看了一下jni_helper3.py，真的是个HTML，可能是我无意中替换了
重新下载，测试了demo，一切正常
抱歉，误报bug
