### ISSUE TITLE
headers/jni.h 内容了重复两遍

### ISSUE THREAD

**Issue by am009** [evilpan/jni_helper#6]
从[1948行](https://github.com/evilpan/jni_helper/blob/master/headers/jni.h#L1948)开始，好像一样的内容又重复了一遍。我拿vscode对比了一下，前后内容完全一样。是不是Ctrl-v按了两次😂。

**Comment by evilpan** [comment]
Fixed in #[8128777](https://github.com/evilpan/jni_helper/commit/8128777f999231601e993c3f0d8ac87dcb8e531d).
